### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/Alejandro-Trave-post-instagram#1]
# Revisión - Aprobado
- [x] Estilo de código y limpieza
# Feedback
- ¡Muy buen trabajo. Felicidades @Atravep  !
## Estilo de código y limpieza
- ¡Muy bien hecho!
## Mejores prácticas/comentarios
- En el styles.css, puedes simplificar el CSS eliminando reglas redundantes y agrupando las propiedades relacionadas.

**Comment by Atravep** [comment]
Gracias Edu, tomo nota!
Saludos y hasta mañana.

**Comment by EduardoHernandezGuzman** [comment]
Muy buen primer proyecto :clap:
